server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true

  client:
    fetch-registry: false
    register-with-eureka: false